name: Build Something Great

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  OTHER_SETTING: def
  EE_VERSION: v1.89.4
  EXTRA_SUFFIX: X01
  OTHER_VAR: abc

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: build it
        run: | # bash
          echo "Hello, World!"